language: node_js
node_js:
  - 12
  - 14
sudo: false
before_install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
install:
  - pnpm install
script:
  - npm run ci-test
notifications:
  email: false
